### ISSUE TITLE
Won't compile on ubuntu 20 or 22

### ISSUE THREAD

**Issue by leem919** [io12/WineBox86.apk#6] opened 2022-06-05 04:38 UTC
On ubuntu 22, I had to use python-is-python3 instead of 2, but I got this same error with both when the building started.

`Scanning dependencies of target dynarec_arm
[  0%] Building C object CMakeFiles/dynarec_arm.dir/src/dynarec/dynablock.c.o
/home/leem919/Downloads/WineBox86.apk/apk-builder/build/box86/src/dynarec/dynablock.c:301:38: warning: tentative definition of variable with internal linkage has incomplete non-array type 'struct __jmp_buf_tag' [-Wtentative-definition-incomplete-type]
static __thread struct __jmp_buf_tag dynarec_jmpbuf;
                                     ^
/home/leem919/Downloads/WineBox86.apk/apk-builder/build/box86/src/dynarec/dynablock.c:301:24: note: forward declaration of 'struct __jmp_buf_tag'
static __thread struct __jmp_buf_tag dynarec_jmpbuf;
                       ^
/home/leem919/Downloads/WineBox86.apk/apk-builder/build/box86/src/dynarec/dynablock.c:305:13: warning: incompatible pointer types passing 'struct __jmp_buf_tag *' to parameter of type 'long *' [-Wincompatible-pointer-types]
    longjmp(&dynarec_jmpbuf, 1);
            ^~~~~~~~~~~~~~~
/home/leem919/Downloads/WineBox86.apk/apk-builder/build/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/setjmp.h:72:33: note: passing argument to parameter '__env' here
__noreturn void longjmp(jmp_buf __env, int __value);
                                ^
/home/leem919/Downloads/WineBox86.apk/apk-builder/build/box86/src/dynarec/dynablock.c:345:18: warning: incompatible pointer types passing 'struct __jmp_buf_tag *' to parameter of type 'long *' [-Wincompatible-pointer-types]
    if(sigsetjmp(&dynarec_jmpbuf, 1)) {
                 ^~~~~~~~~~~~~~~
/home/leem919/Downloads/WineBox86.apk/apk-builder/build/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/setjmp.h:76:26: note: passing argument to parameter '__env' here
int sigsetjmp(sigjmp_buf __env, int __save_signal_mask);
                         ^
/home/leem919/Downloads/WineBox86.apk/apk-builder/build/box86/src/dynarec/dynablock.c:301:38: error: tentative definition has type 'struct __jmp_buf_tag' that is never completed
static __thread struct __jmp_buf_tag dynarec_jmpbuf;
                                     ^
/home/leem919/Downloads/WineBox86.apk/apk-builder/build/box86/src/dynarec/dynablock.c:301:24: note: forward declaration of 'struct __jmp_buf_tag'
static __thread struct __jmp_buf_tag dynarec_jmpbuf;
                       ^
3 warnings and 1 error generated.
make[2]: *** [CMakeFiles/dynarec_arm.dir/build.make:76: CMakeFiles/dynarec_arm.dir/src/dynarec/dynablock.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:150: CMakeFiles/dynarec_arm.dir/all] Error 2
make: *** [Makefile:121: all] Error 2`

**Comment by sl4shed** [comment] 2022-08-13 19:18
happens to me too

**Comment by io12** [comment] 2022-08-20 22:26
Duplicate of https://github.com/io12/WineBox86.apk/issues/3. See that issue for information on the state of the project.

**Closed by io12** 2022-08-20 22:26 UTC
Labels: bug
